# Generated by Django 2.2.2 on 2019-06-21 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=20)),
                ('hide_employer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=20)),
                ('hide_skill', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=35)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=2)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Employer')),
            ],
            options={
                'ordering': ['end_date'],
            },
        ),
    ]
