# Generated by Django 2.2.2 on 2019-06-21 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_string', models.CharField(max_length=100)),
                ('link', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=20)),
                ('degree_type', models.CharField(max_length=5)),
                ('degree_field', models.CharField(max_length=20)),
                ('gpa', models.DecimalField(decimal_places=1, max_digits=2)),
                ('link', models.URLField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='summary',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='BulletPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurb', models.TextField(max_length=500)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Position')),
            ],
        ),
    ]
