# Generated by Django 2.2.2 on 2019-06-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20190620_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
