# Generated by Django 2.2.2 on 2019-06-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20190620_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='hide_employer',
            new_name='hide',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='hide_skill',
            new_name='hide',
        ),
        migrations.AddField(
            model_name='award',
            name='hide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulletpoint',
            name='hide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='hide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='hide',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_field',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='school_name',
            field=models.CharField(max_length=50),
        ),
    ]
