# Generated by Django 2.2.2 on 2019-06-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20190620_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='employer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='position_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_name',
            new_name='name',
        ),
    ]
