version: '3.7'

services:
  
  db:
    image: postgres:latest
    volumes:
      - /data/postgres/:/var/lib/postgresql/data/
    env_file:
      - ./docker/.env.db
  
  web:
    build: .
    command: "gunicorn django_personal_website.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - /data/static:/srv/static
      - /data/media:/srv/media
    env_file:
      - ./docker/.env.web
    ports:
      - 8000:8000
    depends_on:
      - db
      
  certbot:
    build: ./docker/certbot
    volumes: 
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    env_file:
      - ./docker/.env.certbot
    entrypoint: "/entrypoint.sh"
  
  nginx:
    build: ./docker/nginx
    volumes:
      - /data/static/:/srv/static
      - /data/media/:/srv/media
      - /data/certbot/conf:/etc/letsencrypt
      - /data/certbot/www:/var/www/certbot
    env_file:
      - ./docker/.env.nginx
    ports:
      - 80:80
    depends_on:
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  

