version: '3.7'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./docker/.env.db
  
  web:
    build: .
    command: "python /app/manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./docker/.env
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
