version: '3.7'

services:
  
  db:
    image: postgres:latest
    volumes:
      - /data/postgres/:/var/lib/postgresql/data/
    env_file:
      - ./docker/.env.db
  
  web:
    build: .
    command: "gunicorn django_personal_website.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - /data/static:/srv/static
      - /data/media:/srv/media
    env_file:
      - ./docker/.env.prod
    expose:
      - 8000
    depends_on:
      - db
  
  nginx:
    build: ./docker/nginx
    volumes:
      - /data/static/:/srv/static
      - /data/media/:/srv/media
    ports:
      - 80:80
    depends_on:
      - web