# Generated by Django 2.2.2 on 2019-06-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190623_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_alt',
            field=models.CharField(default='No Image alt', max_length=100),
            preserve_default=False,
        ),
    ]
