# Generated by Django 2.2.2 on 2019-06-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20190620_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_name',
            field=models.CharField(max_length=50),
        ),
    ]
